# Test script for Tenacious API with correct tokens
$baseUrl = "https://tenacious-api-master-ovrv8p.laravel.cloud/api"

# Test tokens (the real ones generated by the system)
$tokens = @{
    "test_key_123" = "3|m5p5HVBvBOUHli3HxcF5fq5dRK2AdzJXGU7axF2w379bdbc2"
    "creator_dev_2024" = "4|7hO3kLEoXBnB0LKszuph9e6p7ZLmnNq6MkagLzcQ3ba646d0"
}

Write-Host "=== Tenacious API Test ===" -ForegroundColor Green
Write-Host ""

# Test health endpoint (no auth required)
Write-Host "1. Testing /api/health (no auth required):" -ForegroundColor Yellow
try {
    $healthResponse = Invoke-WebRequest -Method GET -Uri "$baseUrl/health"
    Write-Host "Status: SUCCESS ($($healthResponse.StatusCode))" -ForegroundColor Green
    Write-Host "Response: $($healthResponse.Content)" -ForegroundColor White
} catch {
    Write-Host "Status: FAILED" -ForegroundColor Red
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""

# Test authenticated endpoints
foreach ($tokenName in $tokens.Keys) {
    $token = $tokens[$tokenName]
    Write-Host "2. Testing with token: $tokenName" -ForegroundColor Yellow
    
    # Test products endpoint
    Write-Host "   Testing /api/products:" -ForegroundColor Cyan
    try {
        $productsResponse = Invoke-WebRequest -Method GET -Uri "$baseUrl/products" -Headers @{"Authorization"="Bearer $token"}
        Write-Host "   Status Code: $($productsResponse.StatusCode)" -ForegroundColor Green
        Write-Host "   Response: $($productsResponse.Content.Substring(0, [Math]::Min(200, $productsResponse.Content.Length)))..." -ForegroundColor White
    } catch {
        Write-Host "   Status Code: $($_.Exception.Response.StatusCode.value__)" -ForegroundColor Red
        Write-Host "   Error: $($_.Exception.Message)" -ForegroundColor Red
    }
    Write-Host ""
    
    # Test brand overview endpoint
    Write-Host "   Testing /api/brand/overview:" -ForegroundColor Cyan
    try {
        $brandResponse = Invoke-WebRequest -Method GET -Uri "$baseUrl/brand/overview" -Headers @{"Authorization"="Bearer $token"}
        Write-Host "   Status Code: $($brandResponse.StatusCode)" -ForegroundColor Green
        Write-Host "   Response: $($brandResponse.Content.Substring(0, [Math]::Min(200, $brandResponse.Content.Length)))..." -ForegroundColor White
    } catch {
        Write-Host "   Status Code: $($_.Exception.Response.StatusCode.value__)" -ForegroundColor Red
        Write-Host "   Error: $($_.Exception.Message)" -ForegroundColor Red
    }
    Write-Host ""
}

Write-Host "=== Test Complete ===" -ForegroundColor Green 