<?php

// Test script for Tenacious API with correct tokens
$baseUrl = 'http://localhost:8000/api';

// Test tokens (the real ones generated by the system)
$tokens = [
    'test_key_123' => '3|m5p5HVBvBOUHli3HxcF5fq5dRK2AdzJXGU7axF2w379bdbc2',
    'creator_dev_2024' => '4|7hO3kLEoXBnB0LKszuph9e6p7ZLmnNq6MkagLzcQ3ba646d0'
];

echo "=== Tenacious API Test ===\n\n";

// Test health endpoint (no auth required)
echo "1. Testing /api/health (no auth required):\n";
$healthResponse = file_get_contents($baseUrl . '/health');
echo "Status: " . (http_response_code() === 200 ? "SUCCESS" : "FAILED") . "\n";
echo "Response: " . $healthResponse . "\n\n";

// Test authenticated endpoints
foreach ($tokens as $tokenName => $token) {
    echo "2. Testing with token: $tokenName\n";
    
    // Test products endpoint
    echo "   Testing /api/products:\n";
    $context = stream_context_create([
        'http' => [
            'method' => 'GET',
            'header' => "Authorization: Bearer $token\r\n"
        ]
    ]);
    
    $productsResponse = file_get_contents($baseUrl . '/products', false, $context);
    $statusCode = http_response_code();
    echo "   Status Code: $statusCode\n";
    echo "   Response: " . substr($productsResponse, 0, 200) . "...\n\n";
    
    // Test brand overview endpoint
    echo "   Testing /api/brand/overview:\n";
    $brandResponse = file_get_contents($baseUrl . '/brand/overview', false, $context);
    $statusCode = http_response_code();
    echo "   Status Code: $statusCode\n";
    echo "   Response: " . substr($brandResponse, 0, 200) . "...\n\n";
}

echo "=== Test Complete ===\n"; 