# Test authentication validation endpoint
$baseUrl = "https://tenacious-api-master-ovrv8p.laravel.cloud/api"

# Test tokens (the real ones generated by the system)
$tokens = @{
    "test_key_123" = "3|m5p5HVBvBOUHli3HxcF5fq5dRK2AdzJXGU7axF2w379bdbc2"
    "creator_dev_2024" = "4|7hO3kLEoXBnB0LKszuph9e6p7ZLmnNq6MkagLzcQ3ba646d0"
}

Write-Host "=== Authentication Test ===" -ForegroundColor Green
Write-Host ""

# Test auth validation endpoint
Write-Host "1. Testing /api/auth/validate (no auth required):" -ForegroundColor Yellow
try {
    $authResponse = Invoke-WebRequest -Method GET -Uri "$baseUrl/auth/validate"
    Write-Host "Status: SUCCESS ($($authResponse.StatusCode))" -ForegroundColor Green
    Write-Host "Response: $($authResponse.Content)" -ForegroundColor White
} catch {
    Write-Host "Status: FAILED" -ForegroundColor Red
    Write-Host "Error: $($_.Exception.Message)" -ForegroundColor Red
}
Write-Host ""

# Test authenticated endpoints with each token
foreach ($tokenName in $tokens.Keys) {
    $token = $tokens[$tokenName]
    Write-Host "2. Testing with token: $tokenName" -ForegroundColor Yellow
    
    # Test auth usage endpoint
    Write-Host "   Testing /api/auth/usage:" -ForegroundColor Cyan
    try {
        $usageResponse = Invoke-WebRequest -Method GET -Uri "$baseUrl/auth/usage" -Headers @{"Authorization"="Bearer $token"}
        Write-Host "   Status Code: $($usageResponse.StatusCode)" -ForegroundColor Green
        Write-Host "   Response: $($usageResponse.Content)" -ForegroundColor White
    } catch {
        Write-Host "   Status Code: $($_.Exception.Response.StatusCode.value__)" -ForegroundColor Red
        Write-Host "   Error: $($_.Exception.Message)" -ForegroundColor Red
    }
    Write-Host ""
}

Write-Host "=== Test Complete ===" -ForegroundColor Green 